version: '2' #docker-compose version
services:
  nginx:
    container_name: honestbee_nginx
    image: jyotibhanot30/ubuntu-nginx:latest
    volumes:
      - /var/log/nginx:/var/log/nginx
    ports:
      - "80:80"
  
  fluentd:
    container_name: honestbee_fluentd
    image: jyotibhanot30/ubuntu-fluentd:latest
    environment:
      - AWS_KEY=<access_key> # Do not use double quotes
      - AWS_SECRET=<secret_key> # Do not use double quotes
      - S3_REGION=<region> # Do not use double quotes
      - S3_BUCKET=<s3_bucket> # Do not use double quotes
      - S3_PATH=<s3_folder> #subdirectory # Do not use double quotes
    volumes:
      - /var/log/nginx:/var/log/nginx #Mounting nginx log dir for fluentd
